name: Deploy Function App Code

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2

    - name: 'Build Function App'
      shell: pwsh
      run: dotnet build ./src/FunctionAppCode/FunctionAppCode.sln --configuration Release --output ./output

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: 'Deploy Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.FUNCTION_APP_NAME }}
        package: './output'
    
    - name: Azure logout
      shell: pwsh
      run: az logout